# Generated by Django 3.0.8 on 2020-07-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200716_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
